#!/usr/bin/env sh

# Builds Unison sync tool
# Recommended hardware: scaleway.com, Paris, Starter VC1S instance, Debian Stretch image

# Config
UNISON_VERSION=2.48.4
MAKE_CMD="make UISTYLE=text NATIVE=true STATIC=true"

# Install packages
# - emacs package contains required `etags` executable
sudo apt-get update
sudo apt-get --yes install git
sudo apt-get --yes install emacs
sudo apt-get --yes install ocaml

# Source files
git clone https://github.com/bcpierce00/unison.git
cd unison
git checkout $UNISON_VERSION

# Compilation
$MAKE_CMD

# Build stats
echo Time = `date`
echo uname -a = `uname -a`
echo ocaml -version = `ocaml -version`
echo Make command = $MAKE_CMD
echo unison -version = `./src/unison -version`
echo unison details = `file src/unison`
echo unison-fsmonitor details = `file src/unison-fsmonitor`
